OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
STENO_ENABLE = yes
MOUSEKEY_ENABLE = no
LEADER_ENABLE = yes	
EXTRAFLAGS += -flto
SRC += oneshot.c
SRC += features/casemodes.c